### ISSUE TITLE
Infinite reload bug

### ISSUE THREAD

**Issue by TwilightDuck** [causefx/iDashboard-PHP#1]
I cloned the repo, opened the index.php, logged in with the default password. So far so good.
When I go to settings it gets stuck in an infinite reload with some JSON showing. 
![capture](https://cloud.githubusercontent.com/assets/7328317/14950882/820aeda6-1055-11e6-87a5-d481c4e43438.PNG)

**Comment by TwilightDuck** [comment]
I am using PHP 7 and Nginx 1.8.1

**Comment by NotExpectYet** [comment]
Similar issue myself, running Nginx 1.4.6. 

Have managed to edit the settings.ini.php file though.

**Comment by causefx** [comment]
I didn't test on PHP 7 or 6 for that matter, I will look into this.  @NotExpectYet what PHP version are you running?

**Comment by causefx** [comment]
@SupFrost Can you uncomment out Line 28 on settings.php

`//ini_set('display_errors',1);  error_reporting(E_ALL);`

and reload that page and let me know what happens and if it throws an error.

**Comment by ghost** [comment]
Having the same problem as the others, tried un-commenting, still the same.

Using PHP 7.0.6 and Apache 2.4.20 on Arch.

Looks great so far, can't wait to try it out "for real"!

**Comment by causefx** [comment]
So at least we know it's a PHP 7 code issue.  I'll install 7 on a VM and play with it.

**Comment by causefx** [comment]
@SupFrost @NotExpectYet @gitman47 can you guys try this:

https://github.com/causefx/iDashboard-PHP/releases/tag/0.97

**Comment by causefx** [comment]
@SupFrost @NotExpectYet @gitman47 
This one should fix your problems:  https://github.com/causefx/iDashboard-PHP/archive/0.97-4.zip

**Comment by causefx** [comment]
Resolved in https://github.com/causefx/iDashboard-PHP/archive/0.98.zip
