### ISSUE TITLE
Settings -- Tabs not saving

### ISSUE THREAD

**Issue by mrdeadlocked** [causefx/iDashboard-PHP#11]
I'm having an issue with trying to add/change my tabs. I go into the settings change the tabs/config and when I click save nothing happens.

**Comment by causefx** [comment]
that is very interesting.  What version of PHP are you running?  Are the file permissions set correctly?  Does it display an error when clicking save?

**Comment by mrdeadlocked** [comment]
PHP 7.0.9-1+deb.sury.org~wily+1 (cli) ( NTS ) I was able to setup all of my other tabs initially. Came back a day later and couldnt add anymore. No errors. Here's a gif.

http://i.imgur.com/yDQHjhS.gifv

**Comment by causefx** [comment]
Thank you for the clip. I'm going to do some testing and see what the heck happened.

**Comment by mrdeadlocked** [comment]
Alright. Let m eknow if you want anything tested. Its great so far besides this lil hiccup.

**Comment by causefx** [comment]
ok, so I ran some tests and it looks like it is a permissions issue.  make sure you change the owner to your webserver.

i.e.
`sudo chown -R www-data /var/www/html`

When I had the incorrect permissions it did exactly what yours did.  I'll make sure to code it so it throws an error.  Lemme know.

**Comment by mrdeadlocked** [comment]
I have the permissions setup as follow:

/var/www/html/dash$ ls -l
total 100
-rw-rw-r--  1 admin www-data  2081 Aug  6 20:44 README.md
drwxrwxr-x+ 2 admin www-data  4096 Aug  6 20:44 css
-rw-rw-r--  1 admin www-data   988 Aug  6 20:44 example.ini.php
-rw-rw-r--  1 admin www-data 21297 Aug  6 20:44 favicon.ico
drwxrwxr-x+ 2 admin www-data  4096 Aug  6 20:44 fonts
drwxrwxr-x+ 3 admin www-data  4096 Aug  6 20:44 img
-rw-rw-r--  1 admin www-data  8825 Aug  6 20:44 index.php
drwxrwxr-x+ 2 admin www-data  4096 Aug  6 20:44 js
-rw-r--r--  1 admin www-data  1037 Aug 10 22:15 settings.ini.php
-rw-rw-r--  1 admin www-data 31070 Aug  6 20:44 settings.php
-rw-rw-r--  1 admin www-data  2953 Aug  6 20:44 setup.php

Are the www-data group permissions sufficient?

**Comment by causefx** [comment]
Looks like the settings.ini.php file doesn't have write permission for the group. Chmod 775 for that file.

**Comment by causefx** [comment]
did it work @mrdeadlocked
