### ISSUE TITLE
Cookie or client-based login token ?

### ISSUE THREAD

**Issue by krptg** [causefx/iDashboard-PHP#12]
Hi,

It seems that on my computer if I don't specifically logout from the dashboard, I can access the password protected tabs from any foreign network. Is the login token stored on a cookie or is it server based ? If so is it possible to set some kind of timeout to be sure that after any idle time my dash will always be password protected ?

**Comment by causefx** [comment]
Hi @lgromb currently the cookie is stored on the clients browser for 7 days.  I'm in the process of adding a few feature and I will be sure to include the ability to change the length of the cookie, 

If you would like to modify it yourself, open up settings.php and edit this line:

`//Cookies anyone?
    setcookie("logged", $_POST["password-0"], time() + (86400 * 7), "/");`

change the "7"

**Comment by krptg** [comment]
Hi thanks for the workaround :)

I was just worried that once you login onto the dash somewhere, it stay logged in for anybody from any network. Thanks mate, thanks for the good work and cheers :)

**Comment by causefx** [comment]
Ah, no worries.  I'm glad you like it.
