### ISSUE TITLE
[request]

### ISSUE THREAD

**Issue by rvdwegen** [causefx/iDashboard-PHP#15]
Allow option to have dashboard be full screen instead of with 12px on each side.

Edit: even if just the menu didn't have white space around it the whole thing would feel less cramped.

P.S.
Thank you for the great dashboard!

**Comment by causefx** [comment]
I will code that in :)

**Comment by rvdwegen** [comment]
Thanks ;)

**Comment by rvdwegen** [comment]
Wait, it was already in. Why didn't you tell me :P

**Comment by causefx** [comment]
Oh I thought u were originally talking about the white tiny border. Sorry about that.
