### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by elmerfds** [causefx/iDashboard-PHP#16]
Hi,

Could you add a refresh button similar to how Muximux(https://github.com/Tenzinn3/Managethis) has integrated to their dashboard? 

Currently if I want to reload a just one tab, I would have to hit the refresh button on the browser, which will take me to the default tab. It would be great if you could implement a refresh button that refreshes only the selected frame/tab.

Overall great dashboard, keep it up. Looking forward to what more you could add it, if you need any suggestions let me know.

**Comment by causefx** [comment]
Double click the tab name. :)

**Comment by elmerfds** [comment]
Well I feel really stupid now haha :D

Btw, are you planning on releasing any more features or are you done with this project? Would love something like multiple user support.

Thanks for getting back to me.

**Comment by causefx** [comment]
Yea, i'm planning more stuff, i just need to find more time for it.  Hopefully soon, keep the suggestions coming :)
