### ISSUE TITLE
Text isn't centered

### ISSUE THREAD

**Issue by Codehhh** [causefx/iDashboard-PHP#2]
Some of the text isn't center in the tab.
<img width="902" alt="php" src="https://cloud.githubusercontent.com/assets/12055335/14957112/78c1b1ac-1051-11e6-93be-f236d1594901.png">

It would also be nice to set which row the tabs show up on

**Comment by causefx** [comment]
Thank you, I will look into this.  Also, what is your monitor resolution?

**Comment by Codehhh** [comment]
The resolution that firefox says is 1280x800, but the actual resolution is
2304 x 1440.

**Comment by causefx** [comment]
oh ok, was your browser not full screen or big?

**Comment by Codehhh** [comment]
It was full screen, that's just how OSX down scales the resolution

**Comment by causefx** [comment]
I'll jump on my mac when I get home to test it on that.  800px on width is just too small for this,

**Comment by Codehhh** [comment]
This is what the site looks like on my 1920 x 1080 monitor

![ss 2016-05-02 at 01 23 18](https://cloud.githubusercontent.com/assets/12055335/14961726/17b49b1e-1069-11e6-8a26-bc9699df6b2c.png)

**Comment by causefx** [comment]
is there any gap on both sides?

**Comment by Codehhh** [comment]
Yeah, looks like an even gap on both sides.

![ss](https://cloud.githubusercontent.com/assets/12055335/14962491/132782e2-106d-11e6-8204-471897306c9b.png)

**Comment by causefx** [comment]
ahhhh, time to fix some css...  the box should reach the bottom of your screen which would adjust the width.

**Comment by Codehhh** [comment]
Ah, I was hoping that I would be able to do that. The I find this small screen quite silly

**Comment by causefx** [comment]
yeah, haha.  Should i take the bg pic out and just make it a color or keep the image and make it user select-able?

**Comment by Codehhh** [comment]
I would do both (if possible). I would prefer to have background color selection as well.

**Comment by causefx** [comment]
sounds good :)

**Comment by causefx** [comment]
download the new release when you get a chance.  just overwrite all files, your settings will stay intact.

**Comment by Codehhh** [comment]
New release doesn't load if there is no settings.ini.php, and also doesn't show anything vertically for me.
![ss 2016-05-03 at 02 05 47](https://cloud.githubusercontent.com/assets/12055335/14975811/94b6d658-10d3-11e6-8a4b-8362db895c05.jpg)

**Comment by causefx** [comment]
damn wtf, thats weird...  so your settings.ini.php disappeared?

**Comment by Codehhh** [comment]
I started from a fresh directory to start testing from the beginning. If I had pulled from an existing directory the settings.ini.php would not have been overwritten

**Comment by causefx** [comment]
can you try the new release?  you can start fresh too...

**Comment by Codehhh** [comment]
You fixed it! 
It even looks like this on OSX.
![ss 2016-05-03 at 02 19 51](https://cloud.githubusercontent.com/assets/12055335/14975995/8cd3c458-10d5-11e6-8c2e-a32ac2628706.jpg)

**Comment by causefx** [comment]
Sweet!!!

Add a shit load of tabs and mess around with it...

I'll work on the mobile version next and then cookies.

**Comment by Codehhh** [comment]
New bug(?)

If you make a title larger then the tile it pushes the other tiles off the screen. I noticed this when I added 20+ tabs and then made a tab actually have a name.

![1](https://cloud.githubusercontent.com/assets/12055335/14976124/f9409264-10d6-11e6-9d38-293774aec524.png)
![2](https://cloud.githubusercontent.com/assets/12055335/14976125/f9410b22-10d6-11e6-93b1-8e57cb6318f7.png)

**Comment by causefx** [comment]
holy crap LMAO.  So around 20 tabs is my max huh....  Wonder if I should even attempt to fix that...  good catch either way.

**Comment by Codehhh** [comment]
I mean it's a pretty high limit, but you did say to test with a shit load of tabs :100:

**Comment by causefx** [comment]
haha true that.  I got the mobile layout done now, but the stupid shit wont scroll!  i can scroll on the computer emulating a phone but not on the phone itself... smh

**Comment by Codehhh** [comment]
Maybe it wasn't meant to run on phones!

Nice save cookie "Dashboard"

**Comment by causefx** [comment]
Haha maybe that's true. Lol
