### ISSUE TITLE
Tab issue ipad

### ISSUE THREAD

**Issue by phairplay** [causefx/iDashboard-PHP#20]
Hi I have 9 tabs and on my phone is have a slim bar which drips down when clicked, yet on the ipad I get the box tabs and I'm not able to see all tabs.

Would it be possible to have the phone feature on the ipad?

**Comment by causefx** [comment]
Let me test that out on an iPad.  I will get back to you :)

**Comment by phairplay** [comment]
Hi,
Any luck? :)

**Comment by causefx** [comment]
Just got home from the holidays :)

I'll work on checking this out this week/weekend.

**Comment by phairplay** [comment]
Dude so sorry 
I hope you and your family had a lovely thanksgiving

**Comment by causefx** [comment]
:)

no worries,  I'll get it sorted out :)

**Comment by phairplay** [comment]
Hi fella,
have you had chance to look at this?

**Comment by causefx** [comment]
Hey... what rotation is the iPad when this happens? Or is it both ways?

**Comment by phairplay** [comment]
Both really
Landscape allows me go see only 1 more than portrait

**Comment by causefx** [comment]
And you want the mobile version on that no matter what right.

**Comment by phairplay** [comment]
Yes please :)

**Comment by phairplay** [comment]
Hi,
I've installed version 1.07 everything is fine on my mobile (android) yet I still have an issue while on my iPad. It's doesn't show in groups, meaning I still can't access all the tabs

**Comment by causefx** [comment]
any chance of a screenshot

**Comment by causefx** [comment]
also how many groups do you have setup?

**Comment by phairplay** [comment]
Sorry I was wrong 
9 tabs 
I was only able to see 7
Changing "plex request" to request and "NZBHydra stats" to stats allowed all tabs to be shown 

Many thanks

**Comment by causefx** [comment]
also, you can actually try out groups if you like:

![image](https://cloud.githubusercontent.com/assets/16184466/21196601/67015624-c1f5-11e6-86b3-bffc0e9f8b63.png)

**Comment by phairplay** [comment]
Groups only work when logged in
I have everything set up as guest (for quick viewing) as I'm the only one using this set up

**Comment by causefx** [comment]
ahhh, that makes sense.  I will look into it.
