### ISSUE TITLE
Add drop down menu support

### ISSUE THREAD

**Issue by elmerfds** [causefx/iDashboard-PHP#21]
I've got about 14 tabs(including settings tab), browsing on the desktop at 1920x1080 resolution. If I add any more tabs, they won't show. 

Could you please add support for the tabs to resize accordingly ? or it might be easier and it would look much better to add drop down menu support. Most of my tabs can be grouped. Some less important tabs could be added to the Settings drop down menu if you would add this feature.

Thanks

**Comment by causefx** [comment]
let me think on this,  I may have an easier way to do this.

**Comment by elmerfds** [comment]
OK, thanks for looking into this :)
