### ISSUE TITLE
1.06 Warning: DOMDocument::loadHTMLFile ERROR

### ISSUE THREAD

**Issue by phairplay** [causefx/iDashboard-PHP#22]
Hi Great work on the latest version
when in the settings page i see the following errors 

Warning: DOMDocument::loadHTMLFile(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in C:\nginx-1.8.0\html\settings.php on line 21

Warning: DOMDocument::loadHTMLFile(): I/O warning : failed to load external entity "https://github.com/causefx/iDashboard-PHP/releases/latest" in C:\nginx-1.8.0\html\settings.php on line 21

how can i resolve them

**Comment by phairplay** [comment]
Sorry I have another issue (did want to create another ticket)

On my phone when I hit the drop down I get this

http://m.imgur.com/3nxgg6f

**Comment by causefx** [comment]
on the first:
Uncomment `php_openssl.dll` in the `php.ini`

on the second, yea that is one of the bugs i'm aware of, this update breaks mobile, i'm not concerned with the width issues as much as I am with the javascript not working.  Either way, I'll get both of those fixed before it hits prime time.  Once you uncomment that line restart nginx.  let me know if it worked.

**Comment by phairplay** [comment]
Sorry I can't see php_openssl.dll anywhere

**Comment by causefx** [comment]
is there another php.ini located somewhere else?  nginx folder?

**Comment by phairplay** [comment]
I did a search and there isn't any file php.ini file
What does it do as I have my own ssl_certificate

**Comment by causefx** [comment]
php.ini is where all of you settings for php are stored.  Everything that runs PHP has a php.ini file.  How did you install nginx and php?  

I may look into changing this code and parsing the data another way.

**Comment by phairplay** [comment]
I only have your php file
I installed nginx to proxy and installed php to get access to your set up. 

Sorry I don't really remember how exactly

**Comment by phairplay** [comment]
Looking it up its not a standard 
You need to install it, yet as I mentioned I don't need it I brought an ssl cert

**Comment by causefx** [comment]
openssl allows your server to contact https sites through php.  nothing to do with your cert.  I will look at other ways to code.

**Comment by causefx** [comment]
can you create a php file with this code?

`<?php phpinfo(); ?>`

**Comment by phairplay** [comment]
Done that

**Comment by causefx** [comment]
Can you pat the output

**Comment by phairplay** [comment]
Real noob here, so can you explain that as if I'm 5yrs old :)

**Comment by causefx** [comment]
Also can you create a php file with this code:

```
<?php
$inipath = php_ini_loaded_file();

if ($inipath) {
    echo 'Loaded php.ini: ' . $inipath;
} else {
    echo 'A php.ini file is not loaded';
}
?>
```

That will give you the path to your ini file

**Comment by causefx** [comment]
Save both those files with that code...

Then goto your browser and load up both those pages. Copy the output of both files and paste them here.

**Comment by phairplay** [comment]
the phpinfo is huge and has private info i perfer not to upload. 
i see this "A php.ini file is not loaded"
why is it trying to communicate with another http?

**Comment by causefx** [comment]
ah so there isnt an php.ini loaded.  is there a php.ini-production? or php.ini-development?

**Comment by causefx** [comment]
what do you mean by "why is it trying to communicate with another http?"

**Comment by phairplay** [comment]
Yes there are both :)
Curious as to what it does as I've never needed it (as far as I'm aware)

Edit also the margin option no longer works

**Comment by causefx** [comment]
it loads your php modules.  

So if there isnt a php.ini file in that same directory, do this:

Rename `php.ini-production` to `php.ini`

Open up `php.ini` so you can edit it...

Find this line:
`;extension_dir`

and remove the `;` symbol...

save and restart nginx and then open you the file you created before that said there wasnt a php.ini file loaded.   let me know what it says now.

**Comment by phairplay** [comment]
Loaded php.ini: C:\nginx-1.8.0\php\php.ini

**Comment by causefx** [comment]
perfect, now two things:

does the dashboard load fine now?  if not, open up the page with phpinfo() and look for openssl...   does it say loaded?

**Comment by phairplay** [comment]
All loaded fine
And the errors have gone :)

Are you able to look at the margin option as it doesn't seem to work

I really appericate you Working on this :+1:

**Comment by causefx** [comment]
what happens with margin?

**Comment by causefx** [comment]
also under settings > general... what does yours say?

![image](https://cloud.githubusercontent.com/assets/16184466/21157789/f248ed32-c137-11e6-9996-4c9e4a0b0bfe.png)

**Comment by phairplay** [comment]
Here is the old version
http://m.imgur.com/hKua46U
Here is the new version
http://m.imgur.com/AmfY7iJ

It's yellow saying nul failed to check for update

**Comment by causefx** [comment]
How wide is the browser window?

As for the yellow, what does is say for current version and github version

**Comment by phairplay** [comment]
Screen shots were taken on an iPad, yet it's the same on the mobile all fine on the old version not on the new
1.06

**Comment by causefx** [comment]
Another user requested that the mobile version load on the ipad, I can switch it back now that there is groups.

**Comment by phairplay** [comment]
Yeah that was me :) 
I'm happy with the tabs change

**Comment by causefx** [comment]
LOL, actually that user was you...
https://github.com/causefx/iDashboard-PHP/issues/20

So on your iPad you want the normal version then correct?  And on your phone you want the mobile version?

**Comment by causefx** [comment]
Oh ok gotcha.  Yea I will swap it so the iPad use normal version.  Right now since this new version is still in beta, the swap groups isn't quite working on the mobile version.  Can you do me a favor and let me know once I update the code if the iPad works on the full version with the swap group function.

**Comment by phairplay** [comment]
Oh no
On the old version the htpc page shows all the process info 
On the new version it's as if the margins isn't working, I have to scroll (swipe)

**Comment by phairplay** [comment]
Of course :+1:

**Comment by causefx** [comment]
OK, I will update once I get home.
