### ISSUE TITLE
php-xml required ;)

### ISSUE THREAD

**Issue by ShoGinn** [causefx/iDashboard-PHP#24]
so the default nginx and fastcgi + php doesn't have php-xml by default.

installed it and it fixed the dom errors.

**Comment by causefx** [comment]
You are correct,  I'm currently working on a requirement checker, I will also update the README.  :)

**Comment by ShoGinn** [comment]
No prob, love the project so far!

Everything works except for the settings FYI if you don't have it installed.

**Comment by causefx** [comment]
yea :(  thank you for the kind words :)
