### ISSUE TITLE
About iDashboard

### ISSUE THREAD

**Issue by ShoGinn** [causefx/iDashboard-PHP#27]
I like your settings.php reference to the version, but perhaps you can link back to the github page when clicking on the icon on the left?

Or even just an about portion of the script?

I know these are more mature features for a pre-release.

I am trying to keep this dashboard going since my coding is subpar ;)

**Comment by causefx** [comment]
you want it to link to the main Github page? or just that versions page?

**Comment by ShoGinn** [comment]
Whatever you think! 

Just trying to make it easier for people to get back here and utilize the issue feature.

**Comment by causefx** [comment]
hmmmm, an about portion might work
