### ISSUE TITLE
Settings Page is completely blank

### ISSUE THREAD

**Issue by ciehanski** [causefx/iDashboard-PHP#29]
Hi all,

Just installed iDashboard and not gonna lie it's pretty cool! So thank you for that! I have one issue where when I click on the "Settings" tab, nothing pops up. It's just a blank screen and does not even ask me to login. This is installed on CentOS 7 and is a fresh install. Hopefully we can get this ironed out!

Thanks ahead of time.

**Comment by causefx** [comment]
Can u email me the website link and I will take a look? Causefx at me dot come

**Comment by ciehanski** [comment]
@causefx it is an internal website. Want me to take a screenshot instead?

**Comment by causefx** [comment]
yes please, also of the console log.

**Comment by causefx** [comment]
@moonjazz I had no idea I was on the iDashboard page, i thought this was for my other project.  check out this one when you get time, updated version that's alot better.

https://github.com/causefx/Organizr

**Comment by ciehanski** [comment]
@causefx I have seen it, but personally I like the style of this dashboard much more. This one is easier to look at and has less going on.

**Comment by causefx** [comment]
ahhh ok.  let me know when you get the console output

**Comment by ciehanski** [comment]
Kk. I'm at work now but will post when I am home.

**Comment by causefx** [comment]
same, okie dokie.
