### ISSUE TITLE
Error on settings

### ISSUE THREAD

**Issue by mmolitor87** [causefx/iDashboard-PHP#3]
Ubuntu 14.04.4 LTS
Apache/2.4.7
PHP 5.5.9-1ubuntu4.16 (cli)

Here's what I ran:
git clone https://github.com/causefx/iDashboard-PHP test

chown www-data:www-data test -R

Login and go to settings page to receive:

$section) { if(($keyname == "general")) { $nopass = $section["password"]; } } $salt = substr(str_replace('+','.',base64_encode(md5(mt_rand(), true))),0,16); $rounds = 10000; if(empty($_POST["password-0"])){ $_POST["password-0"] = $nopass;} if(strlen($_POST["password-0"]) < 50){ $_POST["password-0"] = crypt($_POST["password-0"], sprintf('$5$rounds=%d$%s$', $rounds, $salt)); } //password crap $sampleData .= '; Access denied

**Comment by causefx** [comment]
I actually haven't tried cloning.  Let me try now.

**Comment by causefx** [comment]
@mmolitor87 can you try this:
https://github.com/causefx/iDashboard-PHP/releases/tag/0.97

**Comment by hjone72** [comment]
Issue is still exists. Does it matter that I am running this at /dashboard ?

**Comment by causefx** [comment]
It doesn't matter where u run it. I'll keep looking into it.

**Comment by mmolitor87** [comment]
@causefx:

git checkout 851c6ba
Note: checking out '851c6ba'.

Same error happened. :/

Also wanted to let you know that it is happening when I extract a zip as well. So it isn't just a cloning issue.

More fun:

git checkout d27c201 = Infinite reloading issue in the other thread. Means it isn't contained to php 7.0 like you thought in the other thread.

git checkout d27c201 = Only tabs show.

git checkout 9b87b4f = Release I started on, so this issue.

**Comment by causefx** [comment]
@mmolitor87 Thanks for the write up.  Good info.  Shit's got me scratching my had because it throws no errors.

**Comment by mmolitor87** [comment]
@causefx I work in IT helpdesk so I have a good idea of what info is helpful!

It looks to me as if the code isn't parsing properly and is just outputting part of the login code (password handling) right to the page. I don't know enough about php to troubleshoot the code itself, though.

**Comment by causefx** [comment]
You are correct but for some reason it's also reloaded the page, correct?

**Comment by mmolitor87** [comment]
It is NOT reloading the page with this error. It is a constant error shown
with no loading animation.

**Comment by causefx** [comment]
@mmolitor87 can you try this?

https://github.com/causefx/iDashboard-PHP/archive/0.97-2.zip

**Comment by mmolitor87** [comment]
@causefx Well it loads.

![bug](https://cloud.githubusercontent.com/assets/19196123/15062835/eecc9d02-1309-11e6-9f51-0b56836970f9.JPG)

**Comment by causefx** [comment]
LOL, half way there.

**Comment by causefx** [comment]
@mmolitor87 can you do me a favor...?

can you get me the frame source on that tab?  also, can you get me the contents of settings.ini.php?

**Comment by mmolitor87** [comment]
@causefx 

[settings.ini.php.txt](https://github.com/causefx/iDashboard-PHP/files/251478/settings.ini.php.txt)

[source.txt](https://github.com/causefx/iDashboard-PHP/files/251477/source.txt)

Not sure if this is the source you're looking for.

**Comment by causefx** [comment]
@mmolitor87 that source is from the main page, we need it from the frame...

![image](https://cloud.githubusercontent.com/assets/16184466/15062989/fed6e98c-12fa-11e6-9665-8ef219b86ffd.png)

Also, does your settings.ini.php not have line breaks?  
the file you sent looked like this:
![image](https://cloud.githubusercontent.com/assets/16184466/15062997/1f228ad4-12fb-11e6-907b-cba4f4f5ae20.png)

Should look like this:
![image](https://cloud.githubusercontent.com/assets/16184466/15063004/2ef672cc-12fb-11e6-8f08-503dd5aeaf43.png)

**Comment by mmolitor87** [comment]
@causefx 

Here is the frame source: [source.txt](https://github.com/causefx/iDashboard-PHP/files/251481/source.txt)

Open the settings with notepad++ - for some reason the line breaks aren't preserved otherwise.

**Comment by mmolitor87** [comment]
@causefx 

Or this..

`; <?php die("Access denied"); ?>
[general]
title = "iCauseFX"
password = "$5$rounds=10000$2lXstBi0yrcJd7vH$9SBM7jW1XAlS67mNpEKolliHvz57UPgPv65nJIBpgI2"
useicons = "true"
[Sonarr]
url = "https://sonarr.tv/"
icon = "fa-desktop"
enabled = "true"
[QNAP]
url = "https://www.qnap.com/i/useng/"
icon = "fa-cubes"
enabled = "true"
[Movies]
url = "https://couchpota.to/"
icon = "fa-film"
enabled = "true"
[Proxy]
url = "https://www.glype.com/"
icon = "fa-bug"
enabled = "true"
guest = "true"
[Request]
url = "https://plexrequests.8bits.ca/"
icon = "fa-search"
enabled = "true"
guest = "true"
[Server]
url = "https://phpsysinfo.github.io/phpsysinfo/"
icon = "fa-database"
enabled = "true"
[NZB]
url = "https://nzbget.net/"
icon = "fa-cloud-download"
enabled = "true"
`

**Comment by causefx** [comment]
ok, let me do one fix...

**Comment by causefx** [comment]
@mmolitor87 try this:

https://github.com/causefx/iDashboard-PHP/archive/0.97-3.zip

we should have some progress on this...

**Comment by mmolitor87** [comment]
@causefx Some progress:

![bug](https://cloud.githubusercontent.com/assets/19196123/15063335/f8a1d540-130e-11e6-9457-723266a0a26a.JPG)

**Comment by causefx** [comment]
any chance on getting the source again :)

**Comment by mmolitor87** [comment]
[source.txt](https://github.com/causefx/iDashboard-PHP/files/251499/source.txt)

**Comment by causefx** [comment]
dude, you're awesome man!  thanks for helping me...  shits kicking my ass :(

for some reason it isnt switching back to php after the "<?"

**Comment by mmolitor87** [comment]
You're welcome!

I don't know if it matters but line 94 is '            <?$i = 0;'

and 110-112:

```
            <?}
            $i++;
        }?>
```

should the php brackets be separate from other bits of code?

**Comment by causefx** [comment]
@mmolitor87 I have 2 things left to try....

https://github.com/causefx/iDashboard-PHP/archive/0.97-4.zip

**Comment by mmolitor87** [comment]
@causefx No change with that commit on the settings tab. Here's the source just in case:

[source.txt](https://github.com/causefx/iDashboard-PHP/files/251504/source.txt)

**Comment by causefx** [comment]
need the frame source :(

**Comment by mmolitor87** [comment]
D'oh I'm a dummy.

[source.txt](https://github.com/causefx/iDashboard-PHP/files/251505/source.txt)

**Comment by causefx** [comment]
weird, the changes didnt even come thru

**Comment by causefx** [comment]
@mmolitor87 can you refresh your browser?

the code didnt update when you uploaded for some reason....

![image](https://cloud.githubusercontent.com/assets/16184466/15063634/b84707b2-1300-11e6-9d04-8420cca07a5c.png)

should look like that

**Comment by mmolitor87** [comment]
![yay](https://cloud.githubusercontent.com/assets/19196123/15063654/91317c32-1311-11e6-9a4d-210556ce16fa.JPG)

That's because I didn't pull the commit properly. _ashamed_

**Comment by causefx** [comment]
@mmolitor87 

holy shit!!!!  it was a simple fix on my end...  <? -> <?php  which shouldnt matter....  so you're all good now?

**Comment by mmolitor87** [comment]
Yup! Sure am. :) Now for that color picker for all my troubleshooting assistance. ;)

**Comment by causefx** [comment]
hahaha yes!  for sure :)

how do you want it the color changes?  just for the tabs?  different color for active tab? border? background?

**Comment by mmolitor87** [comment]
The tabs/settings page. Since they act as a container those are the only places they would change, really.

My only other idea for you would be a way to individually refresh tabs. :) I don't want to overload you, though.

**Comment by causefx** [comment]
actually on that last commit I added code to start the refresh of tab...  i hope soon to have that done.

**Comment by causefx** [comment]
Resolved in https://github.com/causefx/iDashboard-PHP/archive/0.98.zip
