### ISSUE TITLE
Login wrong password

### ISSUE THREAD

**Issue by hjone72** [causefx/iDashboard-PHP#4]
When I first login the page tells me wrong password "iCauseFX" however still logs in. I then cannot access settings. With the same message as #3 

Thanks

**Comment by causefx** [comment]
It that wrong password is a small bug I need to fix.

**Comment by hjone72** [comment]
Yeah, nothing too major as it is still checking that the password is correct.

**Comment by causefx** [comment]
@hjone72 can you try this?

https://github.com/causefx/iDashboard-PHP/archive/0.97-4.zip

**Comment by hjone72** [comment]
No issue is still there. It did resolve the settings thing as mentioned in #3 

Good work! thanks

**Comment by causefx** [comment]
@hjone72 
Resolved in: https://github.com/causefx/iDashboard-PHP/archive/0.98.zip
