### ISSUE TITLE
Insecure password hashing

### ISSUE THREAD

**Issue by th3fallen** [causefx/iDashboard-PHP#5]
https://github.com/causefx/iDashboard-PHP/blob/master/setup.php#L45 

Please consider using [password_hash](http://php.net/manual/en/function.password-hash.php) for security reasons.

**Comment by causefx** [comment]
thanks for the tip, i'll implement that for v1.0.

**Comment by causefx** [comment]
all done in https://github.com/causefx/iDashboard-PHP/archive/0.99-2.zip
