### ISSUE TITLE
Webmin not displaying

### ISSUE THREAD

**Issue by damianeickhoff** [causefx/iDashboard-PHP#7]
First off all, you did a great job! I like the guest option for my PlexRequest. 

Although I'm also using Webmin. I added this with the correct link, but it won't display the page in the Dashboard.

Any idea what it could be?

**Comment by causefx** [comment]
let me download that and try it on my local machine.

**Comment by causefx** [comment]
@damiantje99 

In the config file (e.g. /etc/webmin/config)

Set: no_frame_options=1

Let me know if this worked for you.

**Comment by damianeickhoff** [comment]
Hmmm, one step closer!

Now i'm getting this 
![capture](https://cloud.githubusercontent.com/assets/12126826/15437788/45ae92b8-1ec9-11e6-8a3b-c4dc0e751088.PNG)

The menu isn't clickable.

**Comment by causefx** [comment]
are there any errors in the console log in your web inspector?

**Comment by damianeickhoff** [comment]
I'm getting this:

![capture](https://cloud.githubusercontent.com/assets/12126826/15438214/597fdcaa-1ecb-11e6-830e-d9f687d83cfc.PNG)

**Comment by causefx** [comment]
have you tried matching the protocols?

**Comment by damianeickhoff** [comment]
So if I got it right, the problem is that Webmin is SSL secured and Dashboard not? Could that be the strange menu problem?

**Comment by causefx** [comment]
i believe so, it will block some elements from not loading.  I serve my dashboard through SSL.

**Comment by damianeickhoff** [comment]
Hmmm, I wan't that too, could it be done with apache only?

**Comment by causefx** [comment]
yes, have it listen to port 443.

**Comment by damianeickhoff** [comment]
Alright, I will look into that, thanks!

**Comment by causefx** [comment]
@damiantje99 did it work out for you?

**Comment by damianeickhoff** [comment]
Can't seem to figure out how to let it listen to 443. Not so much time today, perhaps tomorrow evening, I'll let you know.

**Comment by causefx** [comment]
Sounds good. Let me know if you need help.
