### ISSUE TITLE
[request] favicon for Apple and android

### ISSUE THREAD

**Issue by phairplay** [causefx/iDashboard-PHP#9]
Hi, 
Is it possible to have a favico icon so I can add the website to my home screen on my android and iPad?

**Comment by causefx** [comment]
I'll add this :)

**Comment by Hakker** [comment]
maybe an idea to make it possible to add your own icons. for instance reading an icon dir for it.

**Comment by leram84** [comment]
Have you done this already? I'm interested in this too. Have you seen http://realfavicongenerator.net/ ? They do all the work for you (and then some!), and you could have users just generate their own, and replace the images.

**Comment by causefx** [comment]
I have I just want to do more things as they come up before releasing.

**Comment by leram84** [comment]
did you look at that link? the reason i ask is cause they create every possible variation of favicon/icons you could possibly need in like 10 clicks. They even make windows live tiles for you. Its really cool, and (I think) would be relatively easy for you to add/users to modify. 

(Totally understand if its not a priority, just wanted to put it out there)

**Comment by causefx** [comment]
yup, I checked the link and decided to use it instead :) thanks for that.

**Comment by causefx** [comment]
just checked the tumblr issue, yup its because of https
